import type { Metadata } from "next";
import localFont from "next/font/local";
import { Footer } from "@/shared-ui/Footer";
import { FooterHeading } from "@/shared-ui/FooterHeading";
import { Navigation } from "@/shared-ui/Navigation";
import "./globals.css";

const areaNormal = localFont({
  src: [
    { path: "../public/fonts/Area_Normal_Thin.otf", weight: "100", style: "normal" },
    { path: "../public/fonts/Area_Normal_Thin_Italic.otf", weight: "100", style: "italic" },
    { path: "../public/fonts/Area_Normal_Regular.otf", weight: "300", style: "normal" },
    { path: "../public/fonts/Area_Normal_Regular_Italic.otf", weight: "300", style: "italic" },
    { path: "../public/fonts/Area_Normal_Regular.otf", weight: "400", style: "normal" },
    { path: "../public/fonts/Area_Normal_Regular_Italic.otf", weight: "400", style: "italic" },
    { path: "../public/fonts/Area_Normal_SemiBold.otf", weight: "500", style: "normal" },
    { path: "../public/fonts/Area_Normal_SemiBold_Italic.otf", weight: "500", style: "italic" },
    { path: "../public/fonts/Area_Normal_SemiBold.otf", weight: "600", style: "normal" },
    { path: "../public/fonts/Area_Normal_SemiBold_Italic.otf", weight: "600", style: "italic" },
    { path: "../public/fonts/Area_Normal_Bold.otf", weight: "700", style: "normal" },
    { path: "../public/fonts/Area_Normal_Bold_Italic.otf", weight: "700", style: "italic" },
    { path: "../public/fonts/Area_Normal_ExtraBold.otf", weight: "800", style: "normal" },
    { path: "../public/fonts/Area_Normal_ExtraBold_Italic.otf", weight: "800", style: "italic" },
    { path: "../public/fonts/Area_Normal_Black.otf", weight: "900", style: "normal" },
    { path: "../public/fonts/Area_Normal_Black_Italic.otf", weight: "900", style: "italic" },
  ],
  variable: "--font-area-normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full overflow-x-clip antialiased">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/hvt4ktg.css" />
      </head>
      <body
        suppressHydrationWarning
        className={`${areaNormal.className} ${areaNormal.variable} flex min-h-full flex-col overflow-x-clip bg-white text-zinc-900`}
      >
        <Navigation />
        <div className="relative flex flex-1 flex-col overflow-clip">
          <main className="flex-1">{children}</main>
          <FooterHeading />
          <Footer />
        </div>
      </body>
    </html>
  );
}
