import type { Metadata } from "next";
import { Footer } from "@/shared-ui/Footer";
import { FooterHeading } from "@/shared-ui/FooterHeading";
import { Navigation } from "@/shared-ui/Navigation";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full overflow-x-clip antialiased">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/hvt4ktg.css" />
      </head>
      <body
        suppressHydrationWarning
        className="flex min-h-full flex-col overflow-x-clip bg-white text-zinc-900"
      >
        <Navigation />
        <div className="relative flex flex-1 flex-col overflow-clip">
          <main className="flex-1">{children}</main>
          <FooterHeading />
          <Footer />
        </div>
      </body>
    </html>
  );
}
