export { default as Icon1 } from "./Icon_1.svg";
export { default as Icon2 } from "./Icon_2.svg";
export { default as Icon3 } from "./Icon_3.svg";
export { default as Icon4 } from "./Icon_4.svg";
export { default as Icon5 } from "./Icon_5.svg";
export { default as Icon6 } from "./Icon_6.svg";
export { default as Icon7 } from "./Icon_7.svg";
export { default as Icon8 } from "./Icon_8.svg";
export { default as Icon9 } from "./Icon_9.svg";
export { default as Icon10 } from "./Icon_10.svg";
export { default as Icon11 } from "./Icon_11.svg";
export { default as Icon12 } from "./Icon_12.svg";
export { default as Icon13 } from "./Icon_13.svg";
export { default as Icon14 } from "./Icon_14.svg";
export { default as Icon15 } from "./Icon_15.svg";
// export { default as Icon16 } from "./Icon_16.svg";
// export { default as Icon17 } from "./Icon_17.svg";
// export { default as Icon18 } from "./Icon_18.svg";
// export { default as Icon19 } from "./Icon_19.svg";
//
// export { default as Icon20 } from "./Icon_20.svg";
// export { default as Icon21 } from "./Icon_21.svg";
// export { default as Icon22 } from "./Icon_22.svg";
// export { default as Icon23 } from "./Icon_23.svg";

export { default as Icon24 } from "./Icon_24.svg";
export { default as Icon25 } from "./Icon_25.svg";
export { default as Icon26 } from "./Icon_26.svg";
export { default as Icon27 } from "./Icon_27.svg";
export { default as Icon28 } from "./Icon_28.svg";
export { default as Icon29 } from "./Icon_29.svg";
